### ISSUE TITLE
do not reference a type without exposing it

### ISSUE THREAD

**Issue by BrianHicks** [jfmengels/elm-review-rule-ideas#11]
**What the rule should do:**

Stop you from defining a type (or alias) which is exposed via an annotation but not in `exposing`.

**Example of things the rule would report:**

```elm
module Happiness exposing (toString)


type Happiness
    = Ecstatic
    | FineIGuess
    | Unhappy


toString : Happiness -> String
toString = ...
```

**Example of things the rule would not report:**

```elm
module Happiness exposing (Happiness, toString) -- note additional exposing


type Happiness
    = Ecstatic
    | FineIGuess
    | Unhappy


toString : Happiness -> String
toString = ...
```

**When (not) to enable this rule:**

I can't actually think of times when this wouldn't be helpful! But I've been bit several times by modules which indirectly expose an internal type. It should either have an external form or be completely internal.

**I am looking for:**

Feedback, I suppose. To be honest, I'm not particularly interested in writing this, but if someone else wants to run with the idea I'd happily use it!

**Comment by MartinSStewart** [comment]
This is a good idea. I've already had one case where I released a package and then had to do a minor version bump because I forgot to expose a type used in an exposed function. I'm surprised the compiler itself doesn't enforce this.

**Comment by jfmengels** [comment]
I definitely agree :+1: 

FYI, `jfmengels/review-unused`'s `NoUnused.Exports` rule makes sure not to report a type (in the module's `exposing`) clause if it's present in a type signature, to avoid leading to this problem.

I think this rule makes sense in an application, and I think that for packages it can go a bit further, to warn about the problem that @MartinSStewart mentioned: The rule could read the `elm.json`, and if it sees that it is a package, report non-exposed types that appear in exposed functions/aliases/custom types. Here is an example of [a type that was missing in the package](https://package.elm-lang.org/packages/cuducos/elm-format-number/6.1.0/FormatNumber#humanize) and that [had to be added later](https://package.elm-lang.org/packages/cuducos/elm-format-number/6.2.0/FormatNumber-Humanize).

I'd be willing to have it in [`review-common`](https://github.com/jfmengels/review-common) and to implement it myself (but I'd love a PR if someone wants to try it out).


> I'm surprised the compiler itself doesn't enforce this.

Same here. I'm sure there is an issue about that, but I haven't searched for it (enough to find one).

**Comment by jfmengels** [comment]
This rule has been published here: https://package.elm-lang.org/packages/jfmengels/review-common/latest/NoMissingTypeExpose. Thanks to @sparksp for working on this :)
